services:
  - type: web
    name: chator-frp
    runtime: docker
    repo: https://github.com/mamalubitlal/chator-server
    dockerfilePath: ./frp/Dockerfile
    dockerContext: ./frp
    envVars:
      - key: AUTH_TOKEN
        value: chator-frp-secret
    healthCheckPath: /healthz
