# SIMPLE FAKE Strategy - Simpler, may work better on some ISPs

NFQWS_OPT="--filter-tcp=80,443 --hostlist=/opt/zapret/list/list-general-user.txt --dpi-desync=fake --dpi-desync-repeats=6 --new"

TPWS_OPT="--methodeol"

export NFQWS_OPT TPWS_OPT