# ALT Strategy - Alternative method, good for some ISPs

NFQWS_OPT="--filter-tcp=80,443 --hostlist=/opt/zapret/list/list-general-user.txt --dpi-desync=fake,multisplit --dpi-desync-split-pos=method+2 --dpi-desync-fooling=md5sig --new"

# UDP
NFQWS_OPT="$NFQWS_OPT --filter-udp=443 --hostlist=/opt/zapret/list/list-general-user.txt --dpi-desync=fake --dpi-desync-repeats=6 --new"

TPWS_OPT="--split-pos=1,midsld --disorder"

export NFQWS_OPT TPWS_OPT