FROM alpine:3.19
RUN apk add --no-cache ca-certificates
ARG WSTUNNEL_VERSION=10.5.5
ADD https://github.com/erebe/wstunnel/releases/download/v${WSTUNNEL_VERSION}/wstunnel-${WSTUNNEL_VERSION}-x86_64-unknown-linux-musl.tar.gz /tmp/
RUN cd /tmp && tar xzf wstunnel-${WSTUNNEL_VERSION}-x86_64-unknown-linux-musl.tar.gz \
    && mv wstunnel /usr/local/bin/ \
    && rm -rf /tmp/wstunnel*
COPY frpc-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]
