FROM alpine:3.19
RUN apk add --no-cache ca-certificates
ARG WSTUNNEL_VERSION=10.5.5
ADD https://github.com/erebe/wstunnel/releases/download/v${WSTUNNEL_VERSION}/wstunnel_${WSTUNNEL_VERSION}_linux_amd64.tar.gz /tmp/
RUN cd /tmp && tar xzf wstunnel_${WSTUNNEL_VERSION}_linux_amd64.tar.gz \
    && mv wstunnel /usr/local/bin/ \
    && rm -rf /tmp/wstunnel* \
    && chmod +x /usr/local/bin/wstunnel
COPY frpc-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]
